import Head from 'next/head'
import SearchHeader from '../components/SearchHeader'

function Search() {
    return (
        <div>
            <Head>
                <title>Search Results</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/GoogleLogo.svg" />
            </Head>

            {/* Header */}
            <SearchHeader />

            {/* Search Results */}
            <h1>Search Results</h1>
        </div>
    )

}

export default Search;