import Head from 'next/head'
import Header from '../components/Header'
import { getSession } from 'next-auth/client'

export default function Home({ session }) {
  if (!session) return <Login />

  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="facebook-logo.svg" />
      </Head>

      <Header />

      <main>
        <h1>Sidebar</h1>
        <h1>Posts</h1>
        <h1>Contacts</h1>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  //get user
  const session = await getSession(context);

  return {
    props: {
      session
    }
  }
}
